aws_region            = "us-east-1"
project_name          = "day04-eks"
cluster_name          = "day04-eks-cluster"
cluster_version       = "1.30"
vpc_cidr              = "10.30.0.0/16"
public_subnet_cidrs   = ["10.30.1.0/24", "10.30.2.0/24"]
availability_zones     = ["us-east-1a"]
node_instance_type    = "t3.medium"
node_desired_size     = 1
node_min_size         = 1
node_max_size         = 3
